In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load data using the relative path
df = pd.read_csv('../data/movies_data.csv')

print("Setup Complete! Data loaded successfully.")
df.head()

Setup Complete! Data loaded successfully.


,movie_id,title,tags
0,19995,Avatar,Action Adventure Fantasy Sci-Fi future space war
1,285,Pirates of the Caribbean: At World's End,Action Adventure Fantasy ocean island
2,206647,Spectre,Action Adventure Crime spy secret agent
3,49026,The Dark Knight Rises,Action Crime Drama dc comics batman vigilante
4,49529,John Carter,Action Adventure Sci-Fi mars princess warrior


In [2]:
# Initialize the Vectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

# Transform the 'tags' column into a matrix of numbers
vectors = cv.fit_transform(df['tags']).toarray()

print(f"We now have a matrix of {vectors.shape[0]} movies and {vectors.shape[1]} unique words.")

We now have a matrix of 99 movies and 90 unique words.


In [3]:
# Calculate Cosine Similarity
similarity = cosine_similarity(vectors)

# Preview the similarity matrix
print(similarity)

[[1.         0.47434165 0.28867513 ... 0.         0.         0.20412415]
 [0.47434165 1.         0.36514837 ... 0.         0.         0.        ]
 [0.28867513 0.36514837 1.         ... 0.         0.23570226 0.        ]
 ...
 [0.         0.         0.         ... 1.         0.40824829 0.40824829]
 [0.         0.         0.23570226 ... 0.40824829 1.         0.33333333]
 [0.20412415 0.         0.         ... 0.40824829 0.33333333 1.        ]]


In [5]:
def get_recommendations(movie_name):
    # Find the row index of the movie
    movie_index = df[df['title'] == movie_name].index[0]
    
    # Get the list of similarity scores for that movie
    distances = similarity[movie_index]
    
    # Sort the movies based on similarity scores (highest first)
    # enumerate() keeps track of the original index
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    print(f"If you liked '{movie_name}', you might also like:")
    for i in movie_list:
        print(f"- {df.iloc[i[0]].title}")

# Test the function
get_recommendations('Avatar')

If you liked 'Avatar', you might also like:
- Star Wars
- The Empire Strikes Back
- Return of the Jedi
- Star Wars: Episode I - The Phantom Menace
- Star Wars: Episode II - Attack of the Clones
